security:
  oauth2:
    client:
      clientId: bc60a219aaace89e8421
      clientSecret: a65f7d6507df714d32b9d2e1029ef5b13d6a258a
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource: 
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false
