apiVersion: apps/v1
kind: Deployment

metadata:
    name: conversion-deployment
    labels:
      app: conversion-app
      type: backend-service
spec:
    replicas: 1
    selector:
      matchLabels:  
          app: conversion-app
    template:
      metadata:
        labels:
          app: conversion-app
      spec: 
        containers:
          - name: conversion-service-container
            image: a0c0wk/ft_conversion:1.1
            ports: 
             - containerPort: 8081 
