apiVersion: v1
kind: Service

metadata:
    name: conversion-service
        
spec:    
    ports: 
      - targetPort: 8081
        port: 8081        
    selector:        
          app: conversion-app
            