apiVersion: v1
kind: Service

metadata:
    name: eurekaserver
        
spec:
    type: "LoadBalancer"
    ports: 
      - targetPort: 8761
        port: 8761        
    selector:        
          app: eurekaserver
            
