apiVersion: v1
kind: Service

metadata:
    name: exchange-service
        
spec:
    type: "LoadBalancer"
    ports: 
      - targetPort: 8181
        port: 8181        
    selector:        
          app: exchange-app
            
