apiVersion: v1
kind: Service

metadata:
    name: "zipkin"
        
spec:    
    ports: 
      - targetPort: 9411
        port: 9411        
    selector:        
          app: "zipkin"
    type: "LoadBalancer"
            
