apiVersion: v1
kind: Service

metadata:
    name: zuul-service
        
spec: 
    type: LoadBalancer
    ports: 
      - targetPort: 8765
        port: 8765        
    selector:        
          app: zuul-api-gateway-server
            
